site_name: pyrobotstxt
site_description: Python Package to Create, Analyze and Manipulate Robots.txt Files
site_author: Faisal Shahzad

site_url: https://pyrobotstxt.pages.dev

repo_url: https://github.com/serpwings/pyrobotstxt
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - User Tutorial: tutorial.md
  - Developer Tutorial: developers.md
  - API:
      - ImageAsASCII: imageasascii.md
      - RobotsTxt: robotstxt.md
      - UserAgent: useragent.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - toc:
      permalink: True
  - attr_list
  
theme: readthedocs

copyright: © Copyright 2022 Faisal Shahzad (seowings.org)